name: Node.js CI (Linux - Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run linux CI in dockerfile
      id: linux_ci
      uses: ./.github/actions/run-linux-ci
